update goat

diff --git a/bin/goat b/bin/goat
--- a/bin/goat
+++ b/bin/goat
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ $# -eq 0 ]; then
+    echo "ERROR: goat <appname> [-db {sqlite3 | postgres | mysql}]"
+    exit 1
+fi
+
 APP_NAME=${1:-goatapp}
 shift
 
@@ -12,7 +17,7 @@ do
       if [[ $1 =~ ^--db= ]]; then
         DB=$2
       elif [ -z $2 ]; then
-        echo "'db' requires an argument. (sqlite3 or pg or mysql)" 1>&2
+        echo "ERROR: goat <appname> [-db {sqlite3 | postgres | mysql}]"
         exit 1
       else
         DB=$2
@@ -22,19 +27,11 @@ do
   shift
 done
 
-if [ $DB != "sqlite3" ] && [ $DB != "pg" ] && [ $DB != "mysql" ]; then
-	echo "'db' requires an argument. (sqlite3 or pg or mysql)" 1>&2
+if [ $DB != "sqlite3" ] && [ $DB != "postgres" ] && [ $DB != "mysql" ]; then
+	echo "ERROR: goat <appname> [-db {sqlite3 | postgres | mysql}]"
   exit 1
 fi
 
 git clone https://github.com/kodaimura/goat $APP_NAME
 cd $APP_NAME
 bash _setup/setup.sh $APP_NAME -db $DB
-
-go mod init $APP_NAME
-go mod tidy
-
-echo ""
-echo "config/env/ 内のファイルを設定"
-echo "開発環境では下記コマンドで実行"
-echo "ENV=local go run cmd/$APP_NAME/main.go"
