format

diff --git a/bin/mkscaf b/bin/mkscaf
--- a/bin/mkscaf
+++ b/bin/mkscaf
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-SH_DIR=$(cd "$(dirname "$0")/../sh"; pwd)
+SH_DIR=$(
+  cd "$(dirname "$0")/../sh"
+  pwd
+)
 
 echo -e "\033[1;34m🚀 Create Project Scaffold! 🚀\033[0m"
 echo -e "\033[1;32mChoose a project type:\033[0m"
@@ -12,81 +15,81 @@ read -p "Enter your choice (1-2): " project_type
 echo ""
 
 case $project_type in
-    1)
-        echo -e "\033[1;33mWhat framework do you want to use for the Web Application?\033[0m"
-        echo -e "1. Gin (Go)"
-        echo -e "2. Gin (Go) + Next.js (TypeScript)"
-        echo -e "3. Genie (Julia)"
-        echo -e "4. Genie (Julia) + Next.js (TypeScript)"
-        echo -e "5. Laravel (PHP)"
-        echo -e "\033[1;32mPlease select a number between 1-5:\033[0m"
+1)
+  echo -e "\033[1;33mWhat framework do you want to use for the Web Application?\033[0m"
+  echo -e "1. Gin (Go)"
+  echo -e "2. Gin (Go) + Next.js (TypeScript)"
+  echo -e "3. Genie (Julia)"
+  echo -e "4. Genie (Julia) + Next.js (TypeScript)"
+  echo -e "5. Laravel (PHP)"
+  echo -e "\033[1;32mPlease select a number between 1-5:\033[0m"
 
-        read -p "Enter your choice (1-5): " lang
-        echo ""
+  read -p "Enter your choice (1-5): " lang
+  echo ""
 
-        case $lang in
-            1)
-                echo -e "\033[1;36mScaffolding a Gin web application...\033[0m"
-                $SH_DIR/web-gin.sh
-                ;;
-            2)
-                echo -e "\033[1;36mScaffolding a Gin + Nextjs web application...\033[0m"
-                $SH_DIR/web-gin-next.sh
-                ;;
-            3)
-                echo -e "\033[1;36mScaffolding a Genie web application...\033[0m"
-                $SH_DIR/web-genie.sh
-                ;;
-            4)
-                echo -e "\033[1;36mScaffolding a Genie + Nextjs web application...\033[0m"
-                $SH_DIR/web-genie-next.sh
-                ;;
-            5)
-                echo -e "\033[1;36mScaffolding a Laravel web application...\033[0m"
-                $SH_DIR/web-laravel.sh
-                ;;
-            *)
-                echo -e "\033[1;31m❌ Invalid choice. Please choose a number between 1-5.\033[0m"
-                exit 1
-                ;;
-        esac
-        ;;
-    2)
-        echo -e "\033[1;33mWhat language do you want to use for the Script?\033[0m"
-        echo -e "1. Go"
-        echo -e "2. Julia"
-        echo -e "3. Python"
-        echo -e "4. Racket"
-        echo -e "\033[1;32mPlease select a number between 1-4:\033[0m"
+  case $lang in
+  1)
+    echo -e "\033[1;36mScaffolding a Gin web application...\033[0m"
+    $SH_DIR/web-gin.sh
+    ;;
+  2)
+    echo -e "\033[1;36mScaffolding a Gin + Nextjs web application...\033[0m"
+    $SH_DIR/web-gin-next.sh
+    ;;
+  3)
+    echo -e "\033[1;36mScaffolding a Genie web application...\033[0m"
+    $SH_DIR/web-genie.sh
+    ;;
+  4)
+    echo -e "\033[1;36mScaffolding a Genie + Nextjs web application...\033[0m"
+    $SH_DIR/web-genie-next.sh
+    ;;
+  5)
+    echo -e "\033[1;36mScaffolding a Laravel web application...\033[0m"
+    $SH_DIR/web-laravel.sh
+    ;;
+  *)
+    echo -e "\033[1;31m❌ Invalid choice. Please choose a number between 1-5.\033[0m"
+    exit 1
+    ;;
+  esac
+  ;;
+2)
+  echo -e "\033[1;33mWhat language do you want to use for the Script?\033[0m"
+  echo -e "1. Go"
+  echo -e "2. Julia"
+  echo -e "3. Python"
+  echo -e "4. Racket"
+  echo -e "\033[1;32mPlease select a number between 1-4:\033[0m"
 
-        read -p "Enter your choice (1-4): " lang
-        echo ""
+  read -p "Enter your choice (1-4): " lang
+  echo ""
 
-        case $lang in
-            1)
-                echo -e "\033[1;36mScaffolding a Go script...\033[0m"
-                $SH_DIR/script-go.sh
-                ;;
-            2)
-                echo -e "\033[1;36mScaffolding a Julia script...\033[0m"
-                $SH_DIR/script-julia.sh
-                ;;
-            3)
-                echo -e "\033[1;36mScaffolding a Python script...\033[0m"
-                $SH_DIR/script-python.sh
-                ;;
-            4)
-                echo -e "\033[1;36mScaffolding a Racket script...\033[0m"
-                $SH_DIR/script-racket.sh
-                ;;
-            *)
-                echo -e "\033[1;31m❌ Invalid choice. Please choose a number between 1-4.\033[0m"
-                exit 1
-                ;;
-        esac
-        ;;
-    *)
-        echo -e "\033[1;31m❌ Invalid choice. Please run the script again and choose a number between 1-2.\033[0m"
-        exit 1
-        ;;
+  case $lang in
+  1)
+    echo -e "\033[1;36mScaffolding a Go script...\033[0m"
+    $SH_DIR/script-go.sh
+    ;;
+  2)
+    echo -e "\033[1;36mScaffolding a Julia script...\033[0m"
+    $SH_DIR/script-julia.sh
+    ;;
+  3)
+    echo -e "\033[1;36mScaffolding a Python script...\033[0m"
+    $SH_DIR/script-python.sh
+    ;;
+  4)
+    echo -e "\033[1;36mScaffolding a Racket script...\033[0m"
+    $SH_DIR/script-racket.sh
+    ;;
+  *)
+    echo -e "\033[1;31m❌ Invalid choice. Please choose a number between 1-4.\033[0m"
+    exit 1
+    ;;
+  esac
+  ;;
+*)
+  echo -e "\033[1;31m❌ Invalid choice. Please run the script again and choose a number between 1-2.\033[0m"
+  exit 1
+  ;;
 esac
